name: Test AKS build for a pr from oxpa

permissions:
  contents: read
  id-token: write

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test env
        run: |
          echo main


